name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Docker image and deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Check cluster
      run: kubectl get pods -A

    - name: Build image
      run: |
        eval $(minikube docker-env)
        docker build -t devopshint/node-app:latest .
        docker images

    - name: Deploy to Minikube
      run: kubectl apply -f k8s-node-app.yaml

    - name: Test service URL
      run: |
        minikube service list
        minikube service nodejs-app --url
